### ISSUE TITLE
Add application history feature

### ISSUE THREAD

**Issue by ghost** [Mr-Smarty/BTE-Theme-Parks-BOT#2]
**Add command which returns a list of previous applications for a given user or all recent applications.**

=app history (name) [page]
Returns last 10 applications for a given user. If number of applications exceeds 10, create more pages which can be accessed with the [page] modifier. Should include date/time submitted, status, and application ID.

=app history [page]
Returns the last 10 applications submitted from any user. Subsequent pages can be accessed with the [page] modifier. Should include name, date/time submitted, status, and application ID.

**Comment by Mr-Smarty** [comment]
Sounds good. From now on the application ID will be its row number. That's the easiest and most consistent way.

**Comment by Mr-Smarty** [comment]
Done.
`=app history` last 10 applications.
`=app history [page]` displays 10 applications of that page. If no applications are on the page, the page doesn't exist. If there are less than 10 applications, it will display as many as possible.

Also fixed duplicate names on unreviewed list.
