### ISSUE TITLE
Change the way that multiple applications are handled

### ISSUE THREAD

**Issue by ghost** [Mr-Smarty/BTE-Theme-Parks-BOT#4]
When a user submits a new application, the bot should check if the user has the BUILDER role in the discord.
If so, automatically change the status of the new application to ACCEPTED. _(do not check previous applications)_
If user is **not** a BUILDER, check if the user has any previous applications. 
If yes, change the status of these applications to DENIED. Then, leave the new application as UNREVIEWED.

**Comment by Mr-Smarty** [comment]
Done!
