### ISSUE TITLE
Change the way that denying applications is handled

### ISSUE THREAD

**Issue by ghost** [Mr-Smarty/BTE-Theme-Parks-BOT#5]
When a moderator manually denies an application, change the status of the current application to DENIED. Do not check previous applications and do not demote from builder, as these features are redundant and only reduce performance, as long as [https://github.com/Mr-Smarty/BTE-Theme-Parks-BOT/issues/4](4) is implemented properly.

**Comment by Mr-Smarty** [comment]
So you don't want denial to remove builder role? (For situations when they're accepted, and then reviewers change their mind)

**Comment by ghost** [comment]
No, because the denial command (=app deny) isn't for when reviewers change their mind, it's for reviewing an application. If a reviewer changes their mind, they would use =app edit.

**Comment by Mr-Smarty** [comment]
DONE!
